### PR TITLE
Add build manifest for org.tuxpaint.Tuxpaint

### PR DESCRIPTION
**Pull request by cosimoc**

### CODE REVIEW

**Comment by TingPing** [comment]
- [x] license
- [x] desktop file
- [ ] appdata file (Don't see one?)

**Comment by cosimoc** [comment]
Added one (imported from Fedora) to the PR now.

**Comment by TingPing** [comment]
This fails to build here:
```
========================================================================
Building module SDL_pango in /home/tingping/Projects/flathub/org.tuxpaint.Tuxpaint/.flatpak-builder/build/SDL_pango-1
========================================================================
Applying patch SDL_Pango-0.1.2-API-adds.patch
patching file src/SDL_Pango.c
Hunk #1 FAILED at 723 (different line endings).
Hunk #2 FAILED at 743 (different line endings).
Hunk #3 FAILED at 762 (different line endings).
Hunk #4 FAILED at 1053 (different line endings).
Hunk #5 FAILED at 1067 (different line endings).
5 out of 5 hunks FAILED -- saving rejects to file src/SDL_Pango.c.rej
patching file src/SDL_Pango.h
Hunk #1 FAILED at 109 (different line endings).
Hunk #2 FAILED at 157 (different line endings).
2 out of 2 hunks FAILED -- saving rejects to file src/SDL_Pango.h.rej
Error: module SDL_pango: Child process exited with code 1
```

**Comment by cosimoc** [comment]
Weird! I tried it before and it was building fine here... I will try again in a little bit.

**Comment by cosimoc** [comment]
I just tried again, and it seems to work fine here. What version of flatpak-builder are you using? The error message is also quite odd, since it mentions different line endings...

**Comment by TingPing** [comment]
Flatpak 0.9.2

**Comment by cosimoc** [comment]
OK, I will try later tonight on my F26 machine then.

**Comment by cosimoc** [comment]
Still builds fine here on my Fedora machine.

**Comment by TingPing** [comment]
Weird.. I am on Fedora 26.

**Comment by TingPing** [comment]
Oh well, everything else was fine so repository created: https://github.com/flathub/org.tuxpaint.Tuxpaint

We will see what the builders have to say.

**Pull request closed without merging**
