### PR TITLE
Add SuperTux manifest

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
Works, but it's a bit slow when run inside a VM. Maybe the libglu archive should be hosted in the flathub/org.supertuxproject.SuperTux repo as well.

### CODE REVIEW

**Comment by TingPing** [comment]
At a glance:

- [x] license
- [x] appdata
- [x] desktop

Seems good.

**Comment by matthiasclasen** [comment]
fancy, checkboxes :-)

**Comment by Barthalion** [comment]
I will test the build and then create a repo.

**Comment by Alexander-Wilms** [comment]
Thanks

**Comment by Alexander-Wilms** [comment]
Thanks

**Comment by Alexander-Wilms** [comment]
Sorry, that was caused by the github mobile website

**Comment by Barthalion** [comment]
For some reason the splash screen says "development version" but we can handle this afterwards. Thanks, works like a charm.

**Comment by Barthalion** [comment]
Pushed [here](https://github.com/flathub/org.supertuxproject.SuperTux/commits/master) and added @Alexander-Wilms as collaborator. Buildbot should kick in soon.

**Comment by Alexander-Wilms** [comment]
Yeah, I'm not sure why, since 0.5.1 is labeled as latest stable release. I'll ask on #supertux

**Pull request closed without merging**
