### PR TITLE
Create io.github.Focuswriter.json

### PR DESCRIPTION
**Pull request by Alexander-Wilms**
The author of Focuswriter wasn't interested in supporting Flatpak: https://github.com/gottcode/focuswriter/pull/190

### CODE REVIEW

**Comment by matthiasclasen** [comment]
Doing a quick review by just looking at the sources:
- license: ok, gpl3
- appdata: bad, missing

**Comment by TingPing** [comment]
Depending on KDE master is a problem though.

**Comment by Alexander-Wilms** [comment]
Do we have to wait until there's a first release of the KDE runtime?

Cf. https://cgit.kde.org/flatpak-kde-runtime.git/

**Comment by matthiasclasen** [comment]
We have to wait until the kde runtime is available in flathub. That may or may not coincide with the first release

**Comment by Alexander-Wilms** [comment]
Moved this PR: https://github.com/flathub/flathub/pull/95

**Pull request closed without merging**
